"""empty message

Revision ID: 9e79bcaffa8f
Revises: ffcd3d4964cd
Create Date: 2020-04-14 16:46:39.516627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e79bcaffa8f'
down_revision = 'ffcd3d4964cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('attending', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'attending')
    # ### end Alembic commands ###
