"""empty message

Revision ID: f3853b7c60a6
Revises: 
Create Date: 2020-04-11 19:07:41.876600

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f3853b7c60a6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('events', sa.Column('duration', sa.String(), nullable=True))
    op.add_column('events', sa.Column('equipment', sa.String(), nullable=True))
    op.add_column('events', sa.Column('lat_long', sa.String(), nullable=True))
    op.drop_column('events', 'end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('events', 'lat_long')
    op.drop_column('events', 'equipment')
    op.drop_column('events', 'duration')
    op.drop_column('events', 'date')
    # ### end Alembic commands ###
